// Bộ emoji theo cấu trúc giống Facebook chat picker.
// Mỗi nhóm gồm các emoji kèm keywords tiếng Việt + tiếng Anh để search.
// Khi sửa, giữ field char/keywords gọn, không thêm dấu xuống dòng trong char.

export const EMOJI_GROUPS = [
  {
    key: "smileys",
    label: "Mặt cười & cảm xúc",
    emojis: [
      { char: "😀", keywords: "cuoi happy smile mat cuoi grinning" },
      { char: "😃", keywords: "cuoi happy smile vui grinning" },
      { char: "😄", keywords: "cuoi happy smile grin" },
      { char: "😁", keywords: "cuoi grinning beaming" },
      { char: "😆", keywords: "cuoi laughing satisfied" },
      { char: "😅", keywords: "cuoi sweat smile met" },
      { char: "🤣", keywords: "cuoi rofl rolling laugh haha lol" },
      { char: "😂", keywords: "cuoi joy laugh khoc cuoi tears" },
      { char: "🙂", keywords: "smile slight nhe" },
      { char: "🙃", keywords: "upside down nguoc" },
      { char: "😉", keywords: "wink nhay mat" },
      { char: "😊", keywords: "blush smile happy de thuong" },
      { char: "😇", keywords: "halo angel thien than" },
      { char: "🥰", keywords: "love yeu mat tim heart" },
      { char: "😍", keywords: "love heart eyes yeu" },
      { char: "🤩", keywords: "star eyes sao wow" },
      { char: "😘", keywords: "kiss hon" },
      { char: "😗", keywords: "kiss hon" },
      { char: "☺️", keywords: "smile relax" },
      { char: "😚", keywords: "kiss hon" },
      { char: "😙", keywords: "kiss hon" },
      { char: "🥲", keywords: "smile tear cuoi khoc" },
      { char: "😋", keywords: "yum ngon delicious" },
      { char: "😛", keywords: "tongue le luoi" },
      { char: "😜", keywords: "tongue wink le luoi" },
      { char: "🤪", keywords: "crazy zany dien" },
      { char: "😝", keywords: "tongue squint le luoi" },
      { char: "🤑", keywords: "money tien rich" },
      { char: "🤗", keywords: "hug om" },
      { char: "🤭", keywords: "shy giggle che mieng" },
      { char: "🤫", keywords: "shush im lang" },
      { char: "🤔", keywords: "thinking suy nghi" },
      { char: "🤐", keywords: "zip silent im lang" },
      { char: "🤨", keywords: "raised eyebrow nghi ngo" },
      { char: "😐", keywords: "neutral binh thuong" },
      { char: "😑", keywords: "expressionless vo cam" },
      { char: "😶", keywords: "no mouth khong noi" },
      { char: "😏", keywords: "smirk cuoi tho" },
      { char: "😒", keywords: "unamused chan" },
      { char: "🙄", keywords: "eye roll lac mat" },
      { char: "😬", keywords: "grimace nhan rang" },
      { char: "🤥", keywords: "lying noi doi pinocchio" },
      { char: "😌", keywords: "relieved nhe nhom" },
      { char: "😔", keywords: "pensive buon sad" },
      { char: "😪", keywords: "sleepy buon ngu" },
      { char: "🤤", keywords: "drool chay nuoc dai" },
      { char: "😴", keywords: "sleeping ngu zzz" },
      { char: "😷", keywords: "mask om benh" },
      { char: "🤒", keywords: "thermometer sot om" },
      { char: "🤕", keywords: "head bandage chan thuong" },
      { char: "🤢", keywords: "nauseated buon non" },
      { char: "🤮", keywords: "vomit non" },
      { char: "🤧", keywords: "sneeze hat hoi" },
      { char: "🥵", keywords: "hot nong" },
      { char: "🥶", keywords: "cold lanh" },
      { char: "🥴", keywords: "woozy say chong mat" },
      { char: "😵", keywords: "dizzy chong mat ngat" },
      { char: "🤯", keywords: "exploding mind blown shock" },
      { char: "🤠", keywords: "cowboy" },
      { char: "🥳", keywords: "party tiec sinh nhat" },
      { char: "🥸", keywords: "disguise nguy trang" },
      { char: "😎", keywords: "cool sunglasses ngau" },
      { char: "🤓", keywords: "nerd mot sach" },
      { char: "🧐", keywords: "monocle suy ngam" },
      { char: "😕", keywords: "confused boi roi" },
      { char: "😟", keywords: "worried lo lang" },
      { char: "🙁", keywords: "frown buon" },
      { char: "☹️", keywords: "frowning buon" },
      { char: "😮", keywords: "open mouth ngac nhien" },
      { char: "😯", keywords: "hushed im" },
      { char: "😲", keywords: "astonished kinh ngac" },
      { char: "😳", keywords: "flushed do mat ngai" },
      { char: "🥺", keywords: "pleading nai ni xin" },
      { char: "😦", keywords: "frowning open mouth" },
      { char: "😧", keywords: "anguished dau don" },
      { char: "😨", keywords: "fearful so" },
      { char: "😰", keywords: "anxious lo so mo hoi" },
      { char: "😥", keywords: "sad sweat buon mo hoi" },
      { char: "😢", keywords: "cry khoc" },
      { char: "😭", keywords: "loudly cry khoc to" },
      { char: "😱", keywords: "scream so hai shock" },
      { char: "😖", keywords: "confounded buc boi" },
      { char: "😣", keywords: "persevere co gang" },
      { char: "😞", keywords: "disappointed that vong" },
      { char: "😓", keywords: "downcast met" },
      { char: "😩", keywords: "weary moi met" },
      { char: "😫", keywords: "tired moi met" },
      { char: "🥱", keywords: "yawn ngap" },
      { char: "😤", keywords: "huff buc tuc" },
      { char: "😡", keywords: "rage tuc gian" },
      { char: "😠", keywords: "angry gian" },
      { char: "🤬", keywords: "swearing chui the" },
      { char: "😈", keywords: "smiling devil quy nho" },
      { char: "👿", keywords: "imp angry devil quy" },
      { char: "💀", keywords: "skull dau lau chet" },
      { char: "☠️", keywords: "skull crossbones doc" },
      { char: "💩", keywords: "poo phan poop" },
      { char: "🤡", keywords: "clown he" },
      { char: "👹", keywords: "ogre yeu quai" },
      { char: "👺", keywords: "goblin yeu" },
      { char: "👻", keywords: "ghost ma" },
      { char: "👽", keywords: "alien nguoi ngoai hanh tinh" },
      { char: "👾", keywords: "space invader" },
      { char: "🤖", keywords: "robot" },
      { char: "😺", keywords: "cat smile meo" },
      { char: "😸", keywords: "cat grin meo" },
      { char: "😹", keywords: "cat joy meo cuoi" },
      { char: "😻", keywords: "cat heart meo yeu" },
      { char: "😼", keywords: "cat smirk meo" },
      { char: "😽", keywords: "cat kiss meo hon" },
      { char: "🙀", keywords: "cat scream meo so" },
      { char: "😿", keywords: "cat cry meo khoc" },
      { char: "😾", keywords: "cat pout meo gian" },
    ],
  },
  {
    key: "people",
    label: "Người & cử chỉ",
    emojis: [
      { char: "👋", keywords: "wave vay tay chao hello" },
      { char: "🤚", keywords: "raised hand gio tay" },
      { char: "✋", keywords: "raised hand stop" },
      { char: "🖐️", keywords: "hand fingers" },
      { char: "🖖", keywords: "vulcan salute" },
      { char: "👌", keywords: "ok dong y" },
      { char: "🤌", keywords: "pinched fingers tho gay" },
      { char: "🤏", keywords: "pinching small nho" },
      { char: "✌️", keywords: "victory peace chien thang" },
      { char: "🤞", keywords: "fingers crossed cau may" },
      { char: "🤟", keywords: "love you yeu" },
      { char: "🤘", keywords: "rock metal" },
      { char: "🤙", keywords: "call me goi" },
      { char: "👈", keywords: "left point chi trai" },
      { char: "👉", keywords: "right point chi phai" },
      { char: "👆", keywords: "up point chi len" },
      { char: "👇", keywords: "down point chi xuong" },
      { char: "☝️", keywords: "index point" },
      { char: "👍", keywords: "thumbs up like dong y" },
      { char: "👎", keywords: "thumbs down dislike" },
      { char: "✊", keywords: "raised fist" },
      { char: "👊", keywords: "fist bump dam tay" },
      { char: "🤛", keywords: "left fist" },
      { char: "🤜", keywords: "right fist" },
      { char: "👏", keywords: "clap vo tay" },
      { char: "🙌", keywords: "raised hands celebrate" },
      { char: "👐", keywords: "open hands" },
      { char: "🤲", keywords: "palms up xin" },
      { char: "🤝", keywords: "handshake bat tay" },
      { char: "🙏", keywords: "pray cam on please" },
      { char: "✍️", keywords: "writing viet" },
      { char: "💅", keywords: "nails" },
      { char: "🤳", keywords: "selfie" },
      { char: "💪", keywords: "muscle co bap manh" },
      { char: "🦾", keywords: "mechanical arm" },
      { char: "🦵", keywords: "leg chan" },
      { char: "🦶", keywords: "foot ban chan" },
      { char: "👂", keywords: "ear tai" },
      { char: "👃", keywords: "nose mui" },
      { char: "🧠", keywords: "brain nao" },
      { char: "🦷", keywords: "tooth rang" },
      { char: "🦴", keywords: "bone xuong" },
      { char: "👀", keywords: "eyes mat" },
      { char: "👁️", keywords: "eye mat" },
      { char: "👅", keywords: "tongue luoi" },
      { char: "👄", keywords: "lips moi" },
      { char: "👶", keywords: "baby em be" },
      { char: "🧒", keywords: "child tre em" },
      { char: "👦", keywords: "boy con trai" },
      { char: "👧", keywords: "girl con gai" },
      { char: "🧑", keywords: "person nguoi" },
      { char: "👨", keywords: "man dan ong" },
      { char: "👩", keywords: "woman phu nu" },
      { char: "👴", keywords: "old man cu ong" },
      { char: "👵", keywords: "old woman cu ba" },
      { char: "👮", keywords: "police canh sat" },
      { char: "🕵️", keywords: "detective tham tu" },
      { char: "💂", keywords: "guard" },
      { char: "👷", keywords: "construction cong nhan" },
      { char: "🤴", keywords: "prince hoang tu" },
      { char: "👸", keywords: "princess cong chua" },
      { char: "👰", keywords: "bride co dau" },
      { char: "🤵", keywords: "groom chu re" },
      { char: "👼", keywords: "angel thien than baby" },
      { char: "🎅", keywords: "santa ong gia noel" },
      { char: "🤶", keywords: "mrs claus" },
      { char: "🦸", keywords: "superhero anh hung" },
      { char: "🦹", keywords: "supervillain ke xau" },
      { char: "🧙", keywords: "mage phu thuy" },
      { char: "🧚", keywords: "fairy tien" },
      { char: "🧛", keywords: "vampire ma ca rong" },
      { char: "👨‍💻", keywords: "developer lap trinh vien programmer" },
      { char: "🧑‍💼", keywords: "office worker dan van phong" },
      { char: "👨‍🎓", keywords: "graduate sinh vien tot nghiep" },
      { char: "👩‍🎓", keywords: "graduate sinh vien tot nghiep" },
      { char: "👨‍🏫", keywords: "teacher giao vien" },
      { char: "👩‍🏫", keywords: "teacher giao vien" },
      { char: "👨‍⚕️", keywords: "doctor bac si" },
      { char: "👩‍⚕️", keywords: "doctor bac si" },
      { char: "🧘", keywords: "yoga thien" },
      { char: "🚶", keywords: "walking di bo" },
      { char: "🏃", keywords: "running chay" },
      { char: "💃", keywords: "dancer mua" },
      { char: "🕺", keywords: "dancer mua nam" },
      { char: "👯", keywords: "dancers" },
      { char: "👤", keywords: "silhouette" },
      { char: "👥", keywords: "silhouettes group nhom" },
      { char: "💑", keywords: "couple yeu cap" },
      { char: "💏", keywords: "kiss hon cap" },
      { char: "👪", keywords: "family gia dinh" },
      { char: "👑", keywords: "crown vuong mien" },
    ],
  },
  {
    key: "nature",
    label: "Động vật & thiên nhiên",
    emojis: [
      { char: "🐶", keywords: "dog cho" },
      { char: "🐱", keywords: "cat meo" },
      { char: "🐭", keywords: "mouse chuot" },
      { char: "🐹", keywords: "hamster" },
      { char: "🐰", keywords: "rabbit tho" },
      { char: "🦊", keywords: "fox cao" },
      { char: "🐻", keywords: "bear gau" },
      { char: "🐼", keywords: "panda gau truc" },
      { char: "🐻‍❄️", keywords: "polar bear gau bac cuc" },
      { char: "🐨", keywords: "koala" },
      { char: "🐯", keywords: "tiger ho" },
      { char: "🦁", keywords: "lion su tu" },
      { char: "🐮", keywords: "cow bo" },
      { char: "🐷", keywords: "pig lon heo" },
      { char: "🐽", keywords: "pig nose mui lon" },
      { char: "🐸", keywords: "frog ech" },
      { char: "🐵", keywords: "monkey khi" },
      { char: "🙈", keywords: "see no evil khi che mat" },
      { char: "🙉", keywords: "hear no evil khi che tai" },
      { char: "🙊", keywords: "speak no evil khi che mieng" },
      { char: "🐒", keywords: "monkey khi" },
      { char: "🐔", keywords: "chicken ga" },
      { char: "🐧", keywords: "penguin chim canh cut" },
      { char: "🐦", keywords: "bird chim" },
      { char: "🐤", keywords: "baby chick ga con" },
      { char: "🦆", keywords: "duck vit" },
      { char: "🦅", keywords: "eagle dai bang" },
      { char: "🦉", keywords: "owl cu" },
      { char: "🦇", keywords: "bat doi" },
      { char: "🐺", keywords: "wolf soi" },
      { char: "🐗", keywords: "boar lon rung" },
      { char: "🐴", keywords: "horse face ngua" },
      { char: "🦄", keywords: "unicorn ki lan" },
      { char: "🐝", keywords: "bee ong" },
      { char: "🐛", keywords: "bug sau" },
      { char: "🦋", keywords: "butterfly buom" },
      { char: "🐌", keywords: "snail oc sen" },
      { char: "🐞", keywords: "ladybug bo rua" },
      { char: "🐜", keywords: "ant kien" },
      { char: "🦂", keywords: "scorpion be cap" },
      { char: "🕷️", keywords: "spider nhen" },
      { char: "🐢", keywords: "turtle rua" },
      { char: "🐍", keywords: "snake ran" },
      { char: "🦎", keywords: "lizard than lan" },
      { char: "🦖", keywords: "trex khung long" },
      { char: "🐙", keywords: "octopus bach tuoc" },
      { char: "🦑", keywords: "squid muc" },
      { char: "🦐", keywords: "shrimp tom" },
      { char: "🦞", keywords: "lobster tom hum" },
      { char: "🦀", keywords: "crab cua" },
      { char: "🐡", keywords: "blowfish ca noc" },
      { char: "🐠", keywords: "tropical fish ca" },
      { char: "🐟", keywords: "fish ca" },
      { char: "🐬", keywords: "dolphin ca heo" },
      { char: "🐳", keywords: "whale ca voi" },
      { char: "🦈", keywords: "shark ca map" },
      { char: "🐊", keywords: "crocodile ca sau" },
      { char: "🐅", keywords: "tiger ho" },
      { char: "🐆", keywords: "leopard bao" },
      { char: "🦓", keywords: "zebra ngua van" },
      { char: "🦍", keywords: "gorilla khi dot" },
      { char: "🦧", keywords: "orangutan" },
      { char: "🐘", keywords: "elephant voi" },
      { char: "🦛", keywords: "hippo ha ma" },
      { char: "🦏", keywords: "rhino te giac" },
      { char: "🐪", keywords: "camel lac da" },
      { char: "🦒", keywords: "giraffe huou cao co" },
      { char: "🦘", keywords: "kangaroo chuot tui" },
      { char: "🐃", keywords: "buffalo trau" },
      { char: "🐂", keywords: "ox bo" },
      { char: "🐎", keywords: "horse ngua" },
      { char: "🐖", keywords: "pig heo" },
      { char: "🐐", keywords: "goat de" },
      { char: "🐏", keywords: "ram cuu" },
      { char: "🐑", keywords: "sheep cuu" },
      { char: "🐕", keywords: "dog cho" },
      { char: "🦮", keywords: "guide dog cho dan duong" },
      { char: "🐩", keywords: "poodle" },
      { char: "🌸", keywords: "blossom hoa anh dao" },
      { char: "💮", keywords: "white flower hoa" },
      { char: "🏵️", keywords: "rosette hoa" },
      { char: "🌹", keywords: "rose hoa hong" },
      { char: "🥀", keywords: "wilted rose hoa heo" },
      { char: "🌺", keywords: "hibiscus hoa dam but" },
      { char: "🌻", keywords: "sunflower hoa huong duong" },
      { char: "🌼", keywords: "blossom flower" },
      { char: "🌷", keywords: "tulip" },
      { char: "🌱", keywords: "seedling cay non" },
      { char: "🌲", keywords: "evergreen tree cay thong" },
      { char: "🌳", keywords: "tree cay" },
      { char: "🌴", keywords: "palm tree dua" },
      { char: "🌵", keywords: "cactus xuong rong" },
      { char: "🌾", keywords: "rice lua" },
      { char: "🍀", keywords: "four leaf clover may man" },
      { char: "🍁", keywords: "maple leaf la phong" },
      { char: "🍃", keywords: "leaves la cay" },
      { char: "☀️", keywords: "sun mat troi" },
      { char: "🌙", keywords: "moon mat trang" },
      { char: "⭐", keywords: "star sao" },
      { char: "🌟", keywords: "sparkle star sao sang" },
      { char: "💫", keywords: "dizzy chong mat" },
      { char: "✨", keywords: "sparkles lap lanh" },
      { char: "☁️", keywords: "cloud may" },
      { char: "⛅", keywords: "sun cloud nang nhe" },
      { char: "🌤️", keywords: "sun cloud" },
      { char: "🌧️", keywords: "rain mua" },
      { char: "⛈️", keywords: "storm bao giong" },
      { char: "🌩️", keywords: "lightning sam" },
      { char: "🌨️", keywords: "snow tuyet" },
      { char: "❄️", keywords: "snowflake bong tuyet" },
      { char: "⛄", keywords: "snowman nguoi tuyet" },
      { char: "🌪️", keywords: "tornado loc xoay" },
      { char: "🌫️", keywords: "fog suong mu" },
      { char: "🌈", keywords: "rainbow cau vong" },
      { char: "🔥", keywords: "fire lua hot" },
      { char: "💧", keywords: "drop giot nuoc" },
      { char: "🌊", keywords: "wave song nuoc" },
    ],
  },
  {
    key: "food",
    label: "Đồ ăn & uống",
    emojis: [
      { char: "🍎", keywords: "apple tao" },
      { char: "🍐", keywords: "pear le" },
      { char: "🍊", keywords: "orange cam" },
      { char: "🍋", keywords: "lemon chanh" },
      { char: "🍌", keywords: "banana chuoi" },
      { char: "🍉", keywords: "watermelon dua hau" },
      { char: "🍇", keywords: "grapes nho" },
      { char: "🍓", keywords: "strawberry dau tay" },
      { char: "🫐", keywords: "blueberry viet quat" },
      { char: "🍈", keywords: "melon dua" },
      { char: "🍒", keywords: "cherries anh dao" },
      { char: "🍑", keywords: "peach dao" },
      { char: "🥭", keywords: "mango xoai" },
      { char: "🍍", keywords: "pineapple dua" },
      { char: "🥥", keywords: "coconut dua" },
      { char: "🥝", keywords: "kiwi" },
      { char: "🍅", keywords: "tomato ca chua" },
      { char: "🍆", keywords: "eggplant ca tim" },
      { char: "🥑", keywords: "avocado bo" },
      { char: "🥦", keywords: "broccoli bong cai" },
      { char: "🥬", keywords: "leafy green rau" },
      { char: "🥒", keywords: "cucumber dua leo" },
      { char: "🌶️", keywords: "pepper ot" },
      { char: "🫑", keywords: "bell pepper ot chuong" },
      { char: "🌽", keywords: "corn ngo bap" },
      { char: "🥕", keywords: "carrot ca rot" },
      { char: "🧄", keywords: "garlic toi" },
      { char: "🧅", keywords: "onion hanh" },
      { char: "🥔", keywords: "potato khoai tay" },
      { char: "🍠", keywords: "sweet potato khoai lang" },
      { char: "🥐", keywords: "croissant banh" },
      { char: "🥯", keywords: "bagel" },
      { char: "🍞", keywords: "bread banh mi" },
      { char: "🥖", keywords: "baguette banh mi phap" },
      { char: "🥨", keywords: "pretzel" },
      { char: "🧀", keywords: "cheese pho mai" },
      { char: "🥚", keywords: "egg trung" },
      { char: "🍳", keywords: "fried egg trung op la" },
      { char: "🧈", keywords: "butter bo" },
      { char: "🥞", keywords: "pancakes banh ran" },
      { char: "🧇", keywords: "waffle" },
      { char: "🥓", keywords: "bacon thit xong khoi" },
      { char: "🥩", keywords: "steak thit bo" },
      { char: "🍗", keywords: "poultry leg dui ga" },
      { char: "🍖", keywords: "meat thit" },
      { char: "🌭", keywords: "hot dog" },
      { char: "🍔", keywords: "burger hamburger" },
      { char: "🍟", keywords: "fries khoai chien" },
      { char: "🍕", keywords: "pizza" },
      { char: "🥪", keywords: "sandwich" },
      { char: "🥙", keywords: "kebab stuffed flatbread" },
      { char: "🧆", keywords: "falafel" },
      { char: "🌮", keywords: "taco" },
      { char: "🌯", keywords: "burrito" },
      { char: "🥗", keywords: "salad" },
      { char: "🥘", keywords: "pan paella" },
      { char: "🥫", keywords: "canned food" },
      { char: "🍝", keywords: "spaghetti mi y" },
      { char: "🍜", keywords: "ramen mi" },
      { char: "🍲", keywords: "stew lau" },
      { char: "🍛", keywords: "curry com cari" },
      { char: "🍣", keywords: "sushi" },
      { char: "🍱", keywords: "bento" },
      { char: "🥟", keywords: "dumpling banh bao" },
      { char: "🍤", keywords: "fried shrimp tom chien" },
      { char: "🍙", keywords: "rice ball com nam" },
      { char: "🍚", keywords: "rice com" },
      { char: "🍘", keywords: "rice cracker" },
      { char: "🍢", keywords: "oden" },
      { char: "🍡", keywords: "dango" },
      { char: "🍧", keywords: "shaved ice da bao" },
      { char: "🍨", keywords: "ice cream kem" },
      { char: "🍦", keywords: "soft ice cream kem" },
      { char: "🥧", keywords: "pie banh nuong" },
      { char: "🧁", keywords: "cupcake banh kem" },
      { char: "🍰", keywords: "cake banh kem" },
      { char: "🎂", keywords: "birthday cake banh sinh nhat" },
      { char: "🍮", keywords: "custard banh flan" },
      { char: "🍭", keywords: "lollipop keo mut" },
      { char: "🍬", keywords: "candy keo" },
      { char: "🍫", keywords: "chocolate so co la" },
      { char: "🍿", keywords: "popcorn bap rang" },
      { char: "🍩", keywords: "doughnut banh donut" },
      { char: "🍪", keywords: "cookie banh quy" },
      { char: "🌰", keywords: "chestnut hat de" },
      { char: "🥜", keywords: "peanuts dau phong" },
      { char: "🍯", keywords: "honey mat ong" },
      { char: "🥛", keywords: "milk sua" },
      { char: "🍼", keywords: "baby bottle binh sua" },
      { char: "☕", keywords: "coffee ca phe" },
      { char: "🍵", keywords: "tea tra" },
      { char: "🧃", keywords: "juice nuoc trai cay" },
      { char: "🥤", keywords: "cup straw nuoc ngot" },
      { char: "🧋", keywords: "bubble tea tra sua" },
      { char: "🍶", keywords: "sake ruou nhat" },
      { char: "🍺", keywords: "beer bia" },
      { char: "🍻", keywords: "beers bia" },
      { char: "🥂", keywords: "champagne sam panh" },
      { char: "🍷", keywords: "wine ruou vang" },
      { char: "🥃", keywords: "whiskey ruou" },
      { char: "🍸", keywords: "cocktail" },
      { char: "🍹", keywords: "tropical drink nuoc nhiet doi" },
      { char: "🧉", keywords: "mate" },
      { char: "🍾", keywords: "champagne sam panh no" },
      { char: "🧊", keywords: "ice cube vien da" },
      { char: "🥄", keywords: "spoon thia" },
      { char: "🍴", keywords: "fork knife dia" },
      { char: "🍽️", keywords: "plate dia" },
      { char: "🥢", keywords: "chopsticks dua" },
    ],
  },
  {
    key: "activity",
    label: "Hoạt động & thể thao",
    emojis: [
      { char: "⚽", keywords: "soccer bong da" },
      { char: "🏀", keywords: "basketball bong ro" },
      { char: "🏈", keywords: "american football bong bau duc" },
      { char: "⚾", keywords: "baseball bong chay" },
      { char: "🥎", keywords: "softball" },
      { char: "🎾", keywords: "tennis" },
      { char: "🏐", keywords: "volleyball bong chuyen" },
      { char: "🏉", keywords: "rugby" },
      { char: "🎱", keywords: "billiards bida" },
      { char: "🪀", keywords: "yoyo" },
      { char: "🏓", keywords: "ping pong bong ban" },
      { char: "🏸", keywords: "badminton cau long" },
      { char: "🏒", keywords: "ice hockey" },
      { char: "🏑", keywords: "field hockey" },
      { char: "🥍", keywords: "lacrosse" },
      { char: "🏏", keywords: "cricket" },
      { char: "⛳", keywords: "golf" },
      { char: "🏹", keywords: "bow arrow cung" },
      { char: "🎣", keywords: "fishing cau ca" },
      { char: "🥊", keywords: "boxing" },
      { char: "🥋", keywords: "martial arts vo thuat" },
      { char: "🎽", keywords: "running shirt ao chay" },
      { char: "🛹", keywords: "skateboard van truot" },
      { char: "🛼", keywords: "roller skate giay truot" },
      { char: "🛷", keywords: "sled" },
      { char: "⛸️", keywords: "ice skate giay truot bang" },
      { char: "🥌", keywords: "curling" },
      { char: "🎿", keywords: "ski truot tuyet" },
      { char: "⛷️", keywords: "skier truot tuyet" },
      { char: "🏂", keywords: "snowboarder truot van tuyet" },
      { char: "🏋️", keywords: "weight lifter ta" },
      { char: "🤼", keywords: "wrestlers vat" },
      { char: "🤸", keywords: "cartwheel the duc" },
      { char: "🤺", keywords: "fencing dau kiem" },
      { char: "🤾", keywords: "handball" },
      { char: "🏌️", keywords: "golfer" },
      { char: "🏇", keywords: "horse racing dua ngua" },
      { char: "🧘", keywords: "yoga thien" },
      { char: "🏄", keywords: "surfer luot song" },
      { char: "🏊", keywords: "swimmer boi" },
      { char: "🤽", keywords: "water polo bong nuoc" },
      { char: "🚣", keywords: "rowing cheo thuyen" },
      { char: "🧗", keywords: "climber leo nui" },
      { char: "🚵", keywords: "mountain bike xe dap nui" },
      { char: "🚴", keywords: "biking xe dap" },
      { char: "🏆", keywords: "trophy cup" },
      { char: "🥇", keywords: "gold medal hcv" },
      { char: "🥈", keywords: "silver medal hcb" },
      { char: "🥉", keywords: "bronze medal hcd" },
      { char: "🏅", keywords: "medal huy chuong" },
      { char: "🎖️", keywords: "military medal" },
      { char: "🎗️", keywords: "ribbon ruy bang" },
      { char: "🎫", keywords: "ticket ve" },
      { char: "🎟️", keywords: "admission tickets" },
      { char: "🎪", keywords: "circus rap xiec" },
      { char: "🤹", keywords: "juggling" },
      { char: "🎭", keywords: "performing arts" },
      { char: "🎨", keywords: "art ve" },
      { char: "🎬", keywords: "movie phim" },
      { char: "🎤", keywords: "microphone mic" },
      { char: "🎧", keywords: "headphone tai nghe" },
      { char: "🎼", keywords: "musical score nhac" },
      { char: "🎵", keywords: "musical note nhac" },
      { char: "🎶", keywords: "musical notes nhac" },
      { char: "🎙️", keywords: "studio microphone" },
      { char: "🎚️", keywords: "level slider" },
      { char: "🎛️", keywords: "control knobs" },
      { char: "🎺", keywords: "trumpet ken" },
      { char: "🎷", keywords: "saxophone" },
      { char: "🪗", keywords: "accordion" },
      { char: "🎸", keywords: "guitar" },
      { char: "🪕", keywords: "banjo" },
      { char: "🎻", keywords: "violin" },
      { char: "🥁", keywords: "drum trong" },
      { char: "🎲", keywords: "dice xuc xac" },
      { char: "🎯", keywords: "dart bia" },
      { char: "🎳", keywords: "bowling" },
      { char: "🎮", keywords: "game" },
      { char: "🕹️", keywords: "joystick" },
      { char: "🎰", keywords: "slot machine" },
      { char: "🧩", keywords: "puzzle xep hinh" },
      { char: "🎉", keywords: "party tiec popper" },
      { char: "🎊", keywords: "confetti tiec" },
      { char: "🎈", keywords: "balloon bong bay" },
      { char: "🎁", keywords: "gift qua" },
      { char: "🎀", keywords: "ribbon ruy bang" },
      { char: "🎂", keywords: "birthday cake banh sinh nhat" },
      { char: "🎃", keywords: "halloween bi do" },
      { char: "🎄", keywords: "christmas tree thong noel" },
      { char: "🎆", keywords: "fireworks phao hoa" },
      { char: "🎇", keywords: "sparkler phao bong" },
    ],
  },
  {
    key: "travel",
    label: "Du lịch & địa điểm",
    emojis: [
      { char: "🚗", keywords: "car xe hoi oto" },
      { char: "🚕", keywords: "taxi" },
      { char: "🚙", keywords: "suv" },
      { char: "🚌", keywords: "bus xe buyt" },
      { char: "🚎", keywords: "trolleybus" },
      { char: "🏎️", keywords: "racing car xe dua" },
      { char: "🚓", keywords: "police car xe canh sat" },
      { char: "🚑", keywords: "ambulance xe cuu thuong" },
      { char: "🚒", keywords: "fire engine xe cuu hoa" },
      { char: "🚐", keywords: "minibus" },
      { char: "🛻", keywords: "pickup truck xe ban tai" },
      { char: "🚚", keywords: "truck xe tai" },
      { char: "🚛", keywords: "articulated truck" },
      { char: "🚜", keywords: "tractor" },
      { char: "🏍️", keywords: "motorcycle xe may" },
      { char: "🛵", keywords: "scooter" },
      { char: "🚲", keywords: "bicycle xe dap" },
      { char: "🛴", keywords: "kick scooter" },
      { char: "🛺", keywords: "auto rickshaw" },
      { char: "🚨", keywords: "siren bao dong" },
      { char: "🚔", keywords: "police car canh sat" },
      { char: "🚍", keywords: "bus" },
      { char: "🚘", keywords: "car" },
      { char: "🚖", keywords: "taxi" },
      { char: "🚡", keywords: "aerial tramway cap treo" },
      { char: "🚠", keywords: "mountain cableway" },
      { char: "🚟", keywords: "suspension railway" },
      { char: "🚃", keywords: "railway car" },
      { char: "🚋", keywords: "tram" },
      { char: "🚞", keywords: "mountain railway" },
      { char: "🚝", keywords: "monorail" },
      { char: "🚄", keywords: "high speed train" },
      { char: "🚅", keywords: "bullet train tau cao toc" },
      { char: "🚈", keywords: "light rail" },
      { char: "🚂", keywords: "locomotive dau may" },
      { char: "🚆", keywords: "train tau" },
      { char: "🚇", keywords: "metro" },
      { char: "🚊", keywords: "tram" },
      { char: "🚉", keywords: "station ga" },
      { char: "✈️", keywords: "airplane may bay" },
      { char: "🛫", keywords: "departure cat canh" },
      { char: "🛬", keywords: "arrival ha canh" },
      { char: "🛩️", keywords: "small airplane" },
      { char: "💺", keywords: "seat ghe" },
      { char: "🛰️", keywords: "satellite ve tinh" },
      { char: "🚀", keywords: "rocket ten lua" },
      { char: "🛸", keywords: "ufo" },
      { char: "🚁", keywords: "helicopter truc thang" },
      { char: "🛶", keywords: "canoe thuyen" },
      { char: "⛵", keywords: "sailboat thuyen buom" },
      { char: "🚤", keywords: "speedboat" },
      { char: "🛥️", keywords: "motor boat" },
      { char: "🛳️", keywords: "passenger ship" },
      { char: "⛴️", keywords: "ferry pha" },
      { char: "🚢", keywords: "ship tau thuy" },
      { char: "⚓", keywords: "anchor neo" },
      { char: "⛽", keywords: "fuel pump xang" },
      { char: "🚧", keywords: "construction xay dung" },
      { char: "🚦", keywords: "traffic light den giao thong" },
      { char: "🚥", keywords: "horizontal traffic light" },
      { char: "🗺️", keywords: "world map ban do" },
      { char: "🗿", keywords: "moai tuong" },
      { char: "🗽", keywords: "statue of liberty" },
      { char: "🗼", keywords: "tokyo tower" },
      { char: "🏰", keywords: "castle lau dai" },
      { char: "🏯", keywords: "japanese castle" },
      { char: "🏟️", keywords: "stadium san van dong" },
      { char: "🎡", keywords: "ferris wheel vong xoay" },
      { char: "🎢", keywords: "roller coaster tau luon" },
      { char: "🎠", keywords: "carousel ngua go" },
      { char: "⛲", keywords: "fountain dai phun nuoc" },
      { char: "⛱️", keywords: "umbrella beach o bien" },
      { char: "🏖️", keywords: "beach bai bien" },
      { char: "🏝️", keywords: "desert island dao" },
      { char: "🏜️", keywords: "desert sa mac" },
      { char: "🌋", keywords: "volcano nui lua" },
      { char: "⛰️", keywords: "mountain nui" },
      { char: "🏔️", keywords: "snow mountain nui tuyet" },
      { char: "🗻", keywords: "fuji nui phu si" },
      { char: "🏕️", keywords: "camping cam trai" },
      { char: "⛺", keywords: "tent leu" },
      { char: "🏠", keywords: "house nha" },
      { char: "🏡", keywords: "house with garden" },
      { char: "🏘️", keywords: "houses" },
      { char: "🏚️", keywords: "derelict house nha bo hoang" },
      { char: "🏗️", keywords: "building construction" },
      { char: "🏢", keywords: "office cong ty van phong" },
      { char: "🏣", keywords: "japanese post office" },
      { char: "🏤", keywords: "post office buu dien" },
      { char: "🏥", keywords: "hospital benh vien" },
      { char: "🏦", keywords: "bank ngan hang" },
      { char: "🏨", keywords: "hotel khach san" },
      { char: "🏩", keywords: "love hotel" },
      { char: "🏪", keywords: "convenience store" },
      { char: "🏫", keywords: "school truong hoc" },
      { char: "🏬", keywords: "department store" },
      { char: "🏭", keywords: "factory nha may" },
      { char: "🏛️", keywords: "classical building" },
      { char: "⛪", keywords: "church nha tho" },
      { char: "🕌", keywords: "mosque" },
      { char: "🛕", keywords: "hindu temple" },
      { char: "🕍", keywords: "synagogue" },
      { char: "⛩️", keywords: "shinto shrine" },
      { char: "🕋", keywords: "kaaba" },
      { char: "🌃", keywords: "night stars dem" },
      { char: "🌆", keywords: "sunset thanh pho" },
      { char: "🌇", keywords: "sunset hoang hon" },
      { char: "🌉", keywords: "bridge night cau" },
      { char: "📍", keywords: "pin location dia diem" },
      { char: "🗾", keywords: "japan ban do" },
    ],
  },
  {
    key: "objects",
    label: "Đồ vật & công nghệ",
    emojis: [
      { char: "⌚", keywords: "watch dong ho" },
      { char: "📱", keywords: "phone dien thoai" },
      { char: "📲", keywords: "phone arrow" },
      { char: "💻", keywords: "laptop may tinh" },
      { char: "⌨️", keywords: "keyboard ban phim" },
      { char: "🖥️", keywords: "desktop computer" },
      { char: "🖨️", keywords: "printer may in" },
      { char: "🖱️", keywords: "mouse chuot" },
      { char: "🖲️", keywords: "trackball" },
      { char: "🕹️", keywords: "joystick" },
      { char: "🗜️", keywords: "clamp kep" },
      { char: "💽", keywords: "minidisc" },
      { char: "💾", keywords: "floppy disk dia mem luu" },
      { char: "💿", keywords: "cd dia" },
      { char: "📀", keywords: "dvd" },
      { char: "📼", keywords: "videocassette bang video" },
      { char: "📷", keywords: "camera may anh" },
      { char: "📸", keywords: "camera flash" },
      { char: "📹", keywords: "video camera" },
      { char: "🎥", keywords: "movie camera" },
      { char: "📽️", keywords: "film projector" },
      { char: "🎞️", keywords: "film frames" },
      { char: "📞", keywords: "phone receiver" },
      { char: "☎️", keywords: "telephone" },
      { char: "📟", keywords: "pager" },
      { char: "📠", keywords: "fax machine" },
      { char: "📺", keywords: "tv tivi" },
      { char: "📻", keywords: "radio" },
      { char: "🎙️", keywords: "microphone" },
      { char: "🎚️", keywords: "level slider" },
      { char: "🎛️", keywords: "control knobs" },
      { char: "🧭", keywords: "compass la ban" },
      { char: "⏱️", keywords: "stopwatch dong ho bam giay" },
      { char: "⏲️", keywords: "timer dong ho hen gio" },
      { char: "⏰", keywords: "alarm clock bao thuc" },
      { char: "🕰️", keywords: "mantelpiece clock" },
      { char: "⏳", keywords: "hourglass dong ho cat" },
      { char: "⌛", keywords: "hourglass done" },
      { char: "📡", keywords: "satellite antenna" },
      { char: "🔋", keywords: "battery pin" },
      { char: "🔌", keywords: "plug o cam dien" },
      { char: "💡", keywords: "bulb bong den y tuong" },
      { char: "🔦", keywords: "flashlight den pin" },
      { char: "🕯️", keywords: "candle nen" },
      { char: "🧯", keywords: "fire extinguisher binh chua chay" },
      { char: "🛢️", keywords: "oil drum thung dau" },
      { char: "💸", keywords: "money fly tien bay" },
      { char: "💵", keywords: "dollar tien" },
      { char: "💴", keywords: "yen tien" },
      { char: "💶", keywords: "euro tien" },
      { char: "💷", keywords: "pound tien" },
      { char: "💰", keywords: "money bag tui tien" },
      { char: "💳", keywords: "credit card the tin dung" },
      { char: "💎", keywords: "gem da quy kim cuong" },
      { char: "⚖️", keywords: "balance scale can" },
      { char: "🪜", keywords: "ladder thang" },
      { char: "🧰", keywords: "toolbox hop dung cu" },
      { char: "🔧", keywords: "wrench co le" },
      { char: "🔨", keywords: "hammer bua" },
      { char: "⚒️", keywords: "hammer pick" },
      { char: "🛠️", keywords: "tools dung cu" },
      { char: "⛏️", keywords: "pick cuoc" },
      { char: "🔩", keywords: "nut and bolt" },
      { char: "⚙️", keywords: "gear banh rang" },
      { char: "🧱", keywords: "brick gach" },
      { char: "⛓️", keywords: "chains xich" },
      { char: "🧲", keywords: "magnet nam cham" },
      { char: "🔫", keywords: "water pistol sung" },
      { char: "💣", keywords: "bomb bom" },
      { char: "🧨", keywords: "firecracker phao" },
      { char: "🪓", keywords: "axe riu" },
      { char: "🔪", keywords: "knife dao" },
      { char: "🗡️", keywords: "dagger" },
      { char: "⚔️", keywords: "crossed swords kiem" },
      { char: "🛡️", keywords: "shield khien" },
      { char: "🚬", keywords: "cigarette thuoc la" },
      { char: "⚰️", keywords: "coffin quan tai" },
      { char: "⚱️", keywords: "funeral urn" },
      { char: "🏺", keywords: "amphora binh" },
      { char: "🔮", keywords: "crystal ball qua cau" },
      { char: "📿", keywords: "prayer beads chuoi hat" },
      { char: "🧿", keywords: "nazar amulet bua" },
      { char: "💈", keywords: "barber" },
      { char: "🔭", keywords: "telescope kinh thien van" },
      { char: "🔬", keywords: "microscope kinh hien vi" },
      { char: "🩺", keywords: "stethoscope ong nghe" },
      { char: "💊", keywords: "pill thuoc vien" },
      { char: "💉", keywords: "syringe ong tiem" },
      { char: "🩸", keywords: "blood mau" },
      { char: "🧬", keywords: "dna" },
      { char: "🦠", keywords: "microbe vi khuan" },
      { char: "🧪", keywords: "test tube ong nghiem" },
      { char: "🧫", keywords: "petri dish dia thi nghiem" },
      { char: "🧴", keywords: "lotion bottle" },
      { char: "🧷", keywords: "safety pin" },
      { char: "🧹", keywords: "broom choi" },
      { char: "🧺", keywords: "basket gio" },
      { char: "🧻", keywords: "toilet paper giay" },
      { char: "🧼", keywords: "soap xa phong" },
      { char: "🧽", keywords: "sponge bot bien" },
      { char: "🛏️", keywords: "bed giuong" },
      { char: "🛋️", keywords: "couch sofa" },
      { char: "🪑", keywords: "chair ghe" },
      { char: "🚪", keywords: "door cua" },
      { char: "🛁", keywords: "bathtub bon tam" },
      { char: "🚿", keywords: "shower voi sen" },
      { char: "🚽", keywords: "toilet" },
      { char: "🪒", keywords: "razor dao cao" },
      { char: "🧯", keywords: "fire extinguisher" },
      { char: "🛒", keywords: "shopping cart xe day" },
      { char: "📦", keywords: "package thung hang" },
      { char: "📫", keywords: "mailbox hom thu" },
      { char: "📪", keywords: "mailbox" },
      { char: "📬", keywords: "open mailbox" },
      { char: "📭", keywords: "mailbox empty" },
      { char: "📮", keywords: "postbox hop thu" },
      { char: "📤", keywords: "outbox tray gui" },
      { char: "📥", keywords: "inbox tray nhan" },
      { char: "📨", keywords: "incoming envelope" },
      { char: "📧", keywords: "email thu dien tu" },
      { char: "💌", keywords: "love letter thu tinh" },
      { char: "✉️", keywords: "envelope thu" },
      { char: "📩", keywords: "envelope arrow" },
      { char: "📜", keywords: "scroll cuon giay" },
      { char: "📃", keywords: "page curl" },
      { char: "📄", keywords: "page giay" },
      { char: "📑", keywords: "bookmark tabs" },
      { char: "📊", keywords: "bar chart bieu do" },
      { char: "📈", keywords: "chart up tang" },
      { char: "📉", keywords: "chart down giam" },
      { char: "📰", keywords: "newspaper bao" },
      { char: "🗞️", keywords: "rolled newspaper" },
      { char: "📓", keywords: "notebook so" },
      { char: "📔", keywords: "notebook decorative" },
      { char: "📒", keywords: "ledger" },
      { char: "📕", keywords: "closed book sach" },
      { char: "📗", keywords: "green book sach" },
      { char: "📘", keywords: "blue book sach" },
      { char: "📙", keywords: "orange book sach" },
      { char: "📚", keywords: "books sach" },
      { char: "📖", keywords: "open book mo sach" },
      { char: "🔖", keywords: "bookmark danh dau" },
      { char: "🏷️", keywords: "label nhan" },
      { char: "📂", keywords: "folder thu muc" },
      { char: "📁", keywords: "file folder" },
      { char: "🗂️", keywords: "card index dividers" },
      { char: "📅", keywords: "calendar lich" },
      { char: "📆", keywords: "tear off calendar lich" },
      { char: "🗓️", keywords: "spiral calendar" },
      { char: "📋", keywords: "clipboard ke hoach" },
      { char: "🗒️", keywords: "spiral notepad" },
      { char: "📌", keywords: "pushpin ghim" },
      { char: "📍", keywords: "round pushpin" },
      { char: "📎", keywords: "paperclip kep giay" },
      { char: "🖇️", keywords: "linked paperclips" },
      { char: "📏", keywords: "ruler thuoc" },
      { char: "📐", keywords: "triangular ruler" },
      { char: "✂️", keywords: "scissors keo" },
      { char: "🖊️", keywords: "pen but" },
      { char: "🖋️", keywords: "fountain pen" },
      { char: "✒️", keywords: "ink pen" },
      { char: "🖌️", keywords: "paintbrush co" },
      { char: "🖍️", keywords: "crayon but mau" },
      { char: "📝", keywords: "memo viet ghi chu" },
      { char: "✏️", keywords: "pencil but chi" },
      { char: "🔍", keywords: "search tim kiem magnify" },
      { char: "🔎", keywords: "search" },
      { char: "🔏", keywords: "locked with pen" },
      { char: "🔐", keywords: "locked with key" },
      { char: "🔒", keywords: "locked khoa" },
      { char: "🔓", keywords: "unlocked mo khoa" },
      { char: "🔑", keywords: "key chia khoa" },
      { char: "🗝️", keywords: "old key" },
    ],
  },
  {
    key: "symbols",
    label: "Ký hiệu",
    emojis: [
      { char: "❤️", keywords: "heart yeu tim red" },
      { char: "🧡", keywords: "orange heart tim cam" },
      { char: "💛", keywords: "yellow heart tim vang" },
      { char: "💚", keywords: "green heart tim xanh" },
      { char: "💙", keywords: "blue heart tim xanh" },
      { char: "💜", keywords: "purple heart tim tim" },
      { char: "🖤", keywords: "black heart tim den" },
      { char: "🤍", keywords: "white heart tim trang" },
      { char: "🤎", keywords: "brown heart tim nau" },
      { char: "💔", keywords: "broken heart tim vo" },
      { char: "❣️", keywords: "heart exclamation" },
      { char: "💕", keywords: "two hearts hai tim" },
      { char: "💞", keywords: "revolving hearts" },
      { char: "💓", keywords: "beating heart" },
      { char: "💗", keywords: "growing heart" },
      { char: "💖", keywords: "sparkling heart" },
      { char: "💘", keywords: "heart arrow tim mui ten" },
      { char: "💝", keywords: "heart gift" },
      { char: "💟", keywords: "heart decoration" },
      { char: "♥️", keywords: "heart suit" },
      { char: "♣️", keywords: "club suit" },
      { char: "♠️", keywords: "spade suit" },
      { char: "♦️", keywords: "diamond suit" },
      { char: "🃏", keywords: "joker" },
      { char: "🎴", keywords: "flower playing cards" },
      { char: "🀄", keywords: "mahjong" },
      { char: "💯", keywords: "100 hundred diem 100" },
      { char: "💢", keywords: "anger gian" },
      { char: "💥", keywords: "boom no" },
      { char: "💫", keywords: "dizzy" },
      { char: "💦", keywords: "sweat drop giot mo hoi" },
      { char: "💨", keywords: "dash chay" },
      { char: "🕳️", keywords: "hole lo" },
      { char: "💬", keywords: "speech balloon binh luan chat" },
      { char: "👁️‍🗨️", keywords: "eye in speech bubble" },
      { char: "🗨️", keywords: "left speech bubble" },
      { char: "🗯️", keywords: "right anger bubble" },
      { char: "💭", keywords: "thought balloon suy nghi" },
      { char: "💤", keywords: "zzz ngu" },
      { char: "🚫", keywords: "prohibited cam" },
      { char: "🔞", keywords: "no one under 18" },
      { char: "📵", keywords: "no mobile phones" },
      { char: "🚭", keywords: "no smoking cam hut thuoc" },
      { char: "❗", keywords: "exclamation cham than" },
      { char: "❕", keywords: "white exclamation" },
      { char: "❓", keywords: "question cham hoi" },
      { char: "❔", keywords: "white question" },
      { char: "‼️", keywords: "double exclamation" },
      { char: "⁉️", keywords: "interrobang" },
      { char: "🔅", keywords: "low brightness" },
      { char: "🔆", keywords: "high brightness" },
      { char: "〽️", keywords: "part alternation" },
      { char: "⚠️", keywords: "warning canh bao" },
      { char: "🚸", keywords: "children crossing" },
      { char: "🔱", keywords: "trident" },
      { char: "⚜️", keywords: "fleur de lis" },
      { char: "🔰", keywords: "japanese symbol for beginner" },
      { char: "♻️", keywords: "recycle tai che" },
      { char: "✅", keywords: "check tick dau tich" },
      { char: "🈯", keywords: "reserved" },
      { char: "💹", keywords: "chart yen" },
      { char: "❇️", keywords: "sparkle" },
      { char: "✳️", keywords: "eight pointed asterisk" },
      { char: "❎", keywords: "cross button x" },
      { char: "🌐", keywords: "globe meridians" },
      { char: "💠", keywords: "diamond" },
      { char: "Ⓜ️", keywords: "circled m" },
      { char: "🌀", keywords: "cyclone xoay" },
      { char: "💤", keywords: "zzz" },
      { char: "🏧", keywords: "atm" },
      { char: "🚾", keywords: "wc" },
      { char: "♿", keywords: "wheelchair" },
      { char: "🅿️", keywords: "parking" },
      { char: "🛂", keywords: "passport control" },
      { char: "🛃", keywords: "customs" },
      { char: "🛄", keywords: "baggage claim" },
      { char: "🛅", keywords: "left luggage" },
      { char: "🚹", keywords: "men nam" },
      { char: "🚺", keywords: "women nu" },
      { char: "🚼", keywords: "baby symbol" },
      { char: "🚻", keywords: "restroom wc" },
      { char: "🚮", keywords: "litter rac" },
      { char: "🎦", keywords: "cinema rap chieu phim" },
      { char: "📶", keywords: "antenna bars song" },
      { char: "🈁", keywords: "here" },
      { char: "🔣", keywords: "input symbols" },
      { char: "ℹ️", keywords: "information thong tin" },
      { char: "🔤", keywords: "input latin" },
      { char: "🔡", keywords: "input lowercase" },
      { char: "🔠", keywords: "input uppercase" },
      { char: "🆖", keywords: "ng" },
      { char: "🆗", keywords: "ok" },
      { char: "🆙", keywords: "up" },
      { char: "🆒", keywords: "cool" },
      { char: "🆕", keywords: "new" },
      { char: "🆓", keywords: "free" },
      { char: "0️⃣", keywords: "0 zero" },
      { char: "1️⃣", keywords: "1 one" },
      { char: "2️⃣", keywords: "2 two" },
      { char: "3️⃣", keywords: "3 three" },
      { char: "4️⃣", keywords: "4 four" },
      { char: "5️⃣", keywords: "5 five" },
      { char: "6️⃣", keywords: "6 six" },
      { char: "7️⃣", keywords: "7 seven" },
      { char: "8️⃣", keywords: "8 eight" },
      { char: "9️⃣", keywords: "9 nine" },
      { char: "🔟", keywords: "10 ten" },
      { char: "🔢", keywords: "input numbers so" },
      { char: "#️⃣", keywords: "hash" },
      { char: "*️⃣", keywords: "asterisk" },
      { char: "⏏️", keywords: "eject" },
      { char: "▶️", keywords: "play phat" },
      { char: "⏸️", keywords: "pause tam dung" },
      { char: "⏯️", keywords: "play pause" },
      { char: "⏹️", keywords: "stop dung" },
      { char: "⏺️", keywords: "record ghi am" },
      { char: "⏭️", keywords: "next track tiep theo" },
      { char: "⏮️", keywords: "previous track quay lai" },
      { char: "⏩", keywords: "fast forward" },
      { char: "⏪", keywords: "rewind" },
      { char: "🔼", keywords: "up button" },
      { char: "🔽", keywords: "down button" },
      { char: "➡️", keywords: "right arrow phai" },
      { char: "⬅️", keywords: "left arrow trai" },
      { char: "⬆️", keywords: "up arrow len" },
      { char: "⬇️", keywords: "down arrow xuong" },
      { char: "↗️", keywords: "up right arrow" },
      { char: "↘️", keywords: "down right arrow" },
      { char: "↙️", keywords: "down left arrow" },
      { char: "↖️", keywords: "up left arrow" },
      { char: "↕️", keywords: "up down arrow" },
      { char: "↔️", keywords: "left right arrow" },
      { char: "↩️", keywords: "right curve" },
      { char: "↪️", keywords: "left curve" },
      { char: "⤴️", keywords: "right arrow up" },
      { char: "⤵️", keywords: "right arrow down" },
      { char: "🔃", keywords: "clockwise vertical" },
      { char: "🔄", keywords: "anticlockwise" },
      { char: "🔙", keywords: "back" },
      { char: "🔚", keywords: "end" },
      { char: "🔛", keywords: "on" },
      { char: "🔜", keywords: "soon" },
      { char: "🔝", keywords: "top" },
      { char: "✔️", keywords: "check tick" },
      { char: "❌", keywords: "cross x" },
      { char: "✖️", keywords: "multiply x" },
      { char: "➕", keywords: "plus cong" },
      { char: "➖", keywords: "minus tru" },
      { char: "➗", keywords: "divide chia" },
      { char: "♾️", keywords: "infinity vo cuc" },
      { char: "💲", keywords: "dollar tien" },
      { char: "💱", keywords: "currency exchange ti gia" },
      { char: "™️", keywords: "trademark" },
      { char: "©️", keywords: "copyright" },
      { char: "®️", keywords: "registered" },
      { char: "🔔", keywords: "bell chuong" },
      { char: "🔕", keywords: "no bell" },
      { char: "🎵", keywords: "music note" },
      { char: "🎶", keywords: "music notes" },
      { char: "📢", keywords: "loudspeaker loa" },
      { char: "📣", keywords: "megaphone loa" },
      { char: "📯", keywords: "postal horn" },
      { char: "📜", keywords: "scroll" },
      { char: "🌟", keywords: "star sao" },
      { char: "⭐", keywords: "star" },
      { char: "🔥", keywords: "fire lua" },
      { char: "💯", keywords: "100" },
    ],
  },
];

// Tạo flat list để search
export const ALL_EMOJIS = EMOJI_GROUPS.flatMap((group) =>
  group.emojis.map((emoji) => ({
    ...emoji,
    groupKey: group.key,
    groupLabel: group.label,
  })),
);

// Tìm kiếm emoji theo từ khoá. Chuỗi rỗng → trả về null (UI tự render theo nhóm).
export function searchEmojis(query) {
  const text = String(query || "").trim().toLowerCase();
  if (!text) return null;

  return ALL_EMOJIS.filter((emoji) => {
    if (emoji.char.includes(text)) return true;
    return emoji.keywords.toLowerCase().includes(text);
  });
}

// Quản lý emoji gần đây bằng localStorage.
const RECENT_KEY = "damess.recent.emojis";
const MAX_RECENT = 24;

export function loadRecentEmojis() {
  try {
    const raw = localStorage.getItem(RECENT_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed.slice(0, MAX_RECENT) : [];
  } catch {
    return [];
  }
}

export function pushRecentEmoji(char) {
  if (!char) return [];
  try {
    const current = loadRecentEmojis();
    const next = [char, ...current.filter((item) => item !== char)].slice(0, MAX_RECENT);
    localStorage.setItem(RECENT_KEY, JSON.stringify(next));
    return next;
  } catch {
    return [];
  }
}
